apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: app-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - throskam.dev
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer