// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authentication_methods_query.sql

package orm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthenticationMethod = `-- name: CreateAuthenticationMethod :one
INSERT INTO authentication_methods (provider, sub, user_id) VALUES($1, $2, $3)
RETURNING id, provider, sub, user_id, created_at, updated_at
`

type CreateAuthenticationMethodParams struct {
	Provider AuthenticationProvider
	Sub      string
	UserID   pgtype.UUID
}

// CreateAuthenticationMethod
//
//	INSERT INTO authentication_methods (provider, sub, user_id) VALUES($1, $2, $3)
//	RETURNING id, provider, sub, user_id, created_at, updated_at
func (q *Queries) CreateAuthenticationMethod(ctx context.Context, arg CreateAuthenticationMethodParams) (AuthenticationMethod, error) {
	row := q.db.QueryRow(ctx, createAuthenticationMethod, arg.Provider, arg.Sub, arg.UserID)
	var i AuthenticationMethod
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Sub,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
