// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orm

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthenticationProvider string

const (
	AuthenticationProviderPasswordless AuthenticationProvider = "passwordless"
)

func (e *AuthenticationProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthenticationProvider(s)
	case string:
		*e = AuthenticationProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthenticationProvider: %T", src)
	}
	return nil
}

type NullAuthenticationProvider struct {
	AuthenticationProvider AuthenticationProvider
	Valid                  bool // Valid is true if AuthenticationProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthenticationProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthenticationProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthenticationProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthenticationProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthenticationProvider), nil
}

type AuthenticationMethod struct {
	ID        pgtype.UUID
	Provider  AuthenticationProvider
	Sub       string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Topic struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	ParentID  pgtype.UUID
	ProjectID pgtype.UUID
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
