// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects_query.sql

package orm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id) VALUES($1)
RETURNING id, owner_id, created_at, updated_at
`

// CreateProject
//
//	INSERT INTO projects (owner_id) VALUES($1)
//	RETURNING id, owner_id, created_at, updated_at
func (q *Queries) CreateProject(ctx context.Context, ownerID pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, ownerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT projects.id, projects.owner_id, projects.created_at, projects.updated_at, topics.id, topics.title, topics.content, topics.parent_id, topics.project_id, topics.sort_order, topics.created_at, topics.updated_at, users.id, users.username, users.created_at, users.updated_at FROM projects
JOIN topics ON topics.project_id = projects.id AND topics.parent_id IS NULL
JOIN users ON projects.owner_id = users.id
WHERE projects.id = $1
`

type GetProjectByIDRow struct {
	Project Project
	Topic   Topic
	User    User
}

// GetProjectByID
//
//	SELECT projects.id, projects.owner_id, projects.created_at, projects.updated_at, topics.id, topics.title, topics.content, topics.parent_id, topics.project_id, topics.sort_order, topics.created_at, topics.updated_at, users.id, users.username, users.created_at, users.updated_at FROM projects
//	JOIN topics ON topics.project_id = projects.id AND topics.parent_id IS NULL
//	JOIN users ON projects.owner_id = users.id
//	WHERE projects.id = $1
func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.Project.ID,
		&i.Project.OwnerID,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
		&i.Topic.ID,
		&i.Topic.Title,
		&i.Topic.Content,
		&i.Topic.ParentID,
		&i.Topic.ProjectID,
		&i.Topic.SortOrder,
		&i.Topic.CreatedAt,
		&i.Topic.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwnerWithRoot = `-- name: ListProjectsByOwnerWithRoot :many
SELECT projects.id, projects.owner_id, projects.created_at, projects.updated_at, topics.id, topics.title, topics.content, topics.parent_id, topics.project_id, topics.sort_order, topics.created_at, topics.updated_at FROM projects
JOIN topics ON topics.project_id = projects.id AND topics.parent_id IS NULL
WHERE owner_id = $1
`

type ListProjectsByOwnerWithRootRow struct {
	Project Project
	Topic   Topic
}

// ListProjectsByOwnerWithRoot
//
//	SELECT projects.id, projects.owner_id, projects.created_at, projects.updated_at, topics.id, topics.title, topics.content, topics.parent_id, topics.project_id, topics.sort_order, topics.created_at, topics.updated_at FROM projects
//	JOIN topics ON topics.project_id = projects.id AND topics.parent_id IS NULL
//	WHERE owner_id = $1
func (q *Queries) ListProjectsByOwnerWithRoot(ctx context.Context, ownerID pgtype.UUID) ([]ListProjectsByOwnerWithRootRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwnerWithRoot, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByOwnerWithRootRow{}
	for rows.Next() {
		var i ListProjectsByOwnerWithRootRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.OwnerID,
			&i.Project.CreatedAt,
			&i.Project.UpdatedAt,
			&i.Topic.ID,
			&i.Topic.Title,
			&i.Topic.Content,
			&i.Topic.ParentID,
			&i.Topic.ProjectID,
			&i.Topic.SortOrder,
			&i.Topic.CreatedAt,
			&i.Topic.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectByID = `-- name: RemoveProjectByID :exec
DELETE FROM projects WHERE id = $1
`

// RemoveProjectByID
//
//	DELETE FROM projects WHERE id = $1
func (q *Queries) RemoveProjectByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeProjectByID, id)
	return err
}
