// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics_query.sql

package orm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (title, content, sort_order, parent_id, project_id) VALUES($1, $2, $3, $4, $5)
RETURNING id, title, content, parent_id, project_id, sort_order, created_at, updated_at
`

type CreateTopicParams struct {
	Title     string
	Content   string
	SortOrder int32
	ParentID  pgtype.UUID
	ProjectID pgtype.UUID
}

// CreateTopic
//
//	INSERT INTO topics (title, content, sort_order, parent_id, project_id) VALUES($1, $2, $3, $4, $5)
//	RETURNING id, title, content, parent_id, project_id, sort_order, created_at, updated_at
func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.Title,
		arg.Content,
		arg.SortOrder,
		arg.ParentID,
		arg.ProjectID,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ParentID,
		&i.ProjectID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastSortOrder = `-- name: GetLastSortOrder :one
SELECT sort_order
FROM topics
WHERE parent_id = $1
ORDER BY sort_order DESC
LIMIT 1
`

// GetLastSortOrder
//
//	SELECT sort_order
//	FROM topics
//	WHERE parent_id = $1
//	ORDER BY sort_order DESC
//	LIMIT 1
func (q *Queries) GetLastSortOrder(ctx context.Context, parentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getLastSortOrder, parentID)
	var sort_order int32
	err := row.Scan(&sort_order)
	return sort_order, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT topics.id, topics.title, topics.content, topics.parent_id, topics.project_id, topics.sort_order, topics.created_at, topics.updated_at, projects.id, projects.owner_id, projects.created_at, projects.updated_at FROM topics
JOIN projects ON topics.project_id = projects.id
WHERE topics.id = $1
`

type GetTopicByIDRow struct {
	Topic   Topic
	Project Project
}

// GetTopicByID
//
//	SELECT topics.id, topics.title, topics.content, topics.parent_id, topics.project_id, topics.sort_order, topics.created_at, topics.updated_at, projects.id, projects.owner_id, projects.created_at, projects.updated_at FROM topics
//	JOIN projects ON topics.project_id = projects.id
//	WHERE topics.id = $1
func (q *Queries) GetTopicByID(ctx context.Context, id pgtype.UUID) (GetTopicByIDRow, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i GetTopicByIDRow
	err := row.Scan(
		&i.Topic.ID,
		&i.Topic.Title,
		&i.Topic.Content,
		&i.Topic.ParentID,
		&i.Topic.ProjectID,
		&i.Topic.SortOrder,
		&i.Topic.CreatedAt,
		&i.Topic.UpdatedAt,
		&i.Project.ID,
		&i.Project.OwnerID,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
	)
	return i, err
}

const listTopicAncestors = `-- name: ListTopicAncestors :many
WITH RECURSIVE ancestors AS (
    -- Base case: select the topic itself
    SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
    FROM topics
    WHERE topics.id = $1

    UNION ALL

    -- Recursive case: select the parent of the current topic
    SELECT t.id, t.title, t.content, t.parent_id, t.project_id, t.sort_order, t.created_at, t.updated_at
    FROM topics t
    INNER JOIN ancestors a ON t.id = a.parent_id
)
SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
FROM ancestors
`

type ListTopicAncestorsRow struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	ParentID  pgtype.UUID
	ProjectID pgtype.UUID
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ListTopicAncestors
//
//	WITH RECURSIVE ancestors AS (
//	    -- Base case: select the topic itself
//	    SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
//	    FROM topics
//	    WHERE topics.id = $1
//
//	    UNION ALL
//
//	    -- Recursive case: select the parent of the current topic
//	    SELECT t.id, t.title, t.content, t.parent_id, t.project_id, t.sort_order, t.created_at, t.updated_at
//	    FROM topics t
//	    INNER JOIN ancestors a ON t.id = a.parent_id
//	)
//	SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
//	FROM ancestors
func (q *Queries) ListTopicAncestors(ctx context.Context, id pgtype.UUID) ([]ListTopicAncestorsRow, error) {
	rows, err := q.db.Query(ctx, listTopicAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicAncestorsRow{}
	for rows.Next() {
		var i ListTopicAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.ProjectID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicChildren = `-- name: ListTopicChildren :many
SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at FROM topics
WHERE topics.parent_id = $1
`

// ListTopicChildren
//
//	SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at FROM topics
//	WHERE topics.parent_id = $1
func (q *Queries) ListTopicChildren(ctx context.Context, parentID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.ProjectID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicDescendants = `-- name: ListTopicDescendants :many
WITH RECURSIVE descendants AS (
    -- Base case: select the topic itself
    SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
    FROM topics
    WHERE topics.id = $1

    UNION ALL

    -- Recursive case: select the children of the current topic
    SELECT t.id, t.title, t.content, t.parent_id, t.project_id, t.sort_order, t.created_at, t.updated_at
    FROM topics t
    INNER JOIN descendants a ON t.parent_id = a.id
)
SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
FROM descendants
ORDER BY sort_order ASC
`

type ListTopicDescendantsRow struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	ParentID  pgtype.UUID
	ProjectID pgtype.UUID
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ListTopicDescendants
//
//	WITH RECURSIVE descendants AS (
//	    -- Base case: select the topic itself
//	    SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
//	    FROM topics
//	    WHERE topics.id = $1
//
//	    UNION ALL
//
//	    -- Recursive case: select the children of the current topic
//	    SELECT t.id, t.title, t.content, t.parent_id, t.project_id, t.sort_order, t.created_at, t.updated_at
//	    FROM topics t
//	    INNER JOIN descendants a ON t.parent_id = a.id
//	)
//	SELECT id, title, content, parent_id, project_id, sort_order, created_at, updated_at
//	FROM descendants
//	ORDER BY sort_order ASC
func (q *Queries) ListTopicDescendants(ctx context.Context, id pgtype.UUID) ([]ListTopicDescendantsRow, error) {
	rows, err := q.db.Query(ctx, listTopicDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicDescendantsRow{}
	for rows.Next() {
		var i ListTopicDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ParentID,
			&i.ProjectID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTopic = `-- name: MoveTopic :exec
UPDATE topics
SET parent_id = $1, sort_order = $2
WHERE id = $3
`

type MoveTopicParams struct {
	ParentID  pgtype.UUID
	SortOrder int32
	ID        pgtype.UUID
}

// MoveTopic
//
//	UPDATE topics
//	SET parent_id = $1, sort_order = $2
//	WHERE id = $3
func (q *Queries) MoveTopic(ctx context.Context, arg MoveTopicParams) error {
	_, err := q.db.Exec(ctx, moveTopic, arg.ParentID, arg.SortOrder, arg.ID)
	return err
}

const reindexTopics = `-- name: ReindexTopics :exec
WITH reordered_topics AS (
    SELECT
        id,
        parent_id,
        ROW_NUMBER() OVER (PARTITION BY parent_id ORDER BY sort_order) AS new_sort_order
    FROM topics
    WHERE project_id = $1
)
UPDATE topics
SET sort_order = reordered_topics.new_sort_order
FROM reordered_topics
WHERE topics.id = reordered_topics.id AND topics.project_id = $1
`

// ReindexTopics
//
//	WITH reordered_topics AS (
//	    SELECT
//	        id,
//	        parent_id,
//	        ROW_NUMBER() OVER (PARTITION BY parent_id ORDER BY sort_order) AS new_sort_order
//	    FROM topics
//	    WHERE project_id = $1
//	)
//	UPDATE topics
//	SET sort_order = reordered_topics.new_sort_order
//	FROM reordered_topics
//	WHERE topics.id = reordered_topics.id AND topics.project_id = $1
func (q *Queries) ReindexTopics(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reindexTopics, projectID)
	return err
}

const removeTopicByID = `-- name: RemoveTopicByID :exec
DELETE FROM topics WHERE id = $1
`

// RemoveTopicByID
//
//	DELETE FROM topics WHERE id = $1
func (q *Queries) RemoveTopicByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTopicByID, id)
	return err
}

const removeTopicsByProjectID = `-- name: RemoveTopicsByProjectID :exec
DELETE FROM topics WHERE project_id = $1
`

// RemoveTopicsByProjectID
//
//	DELETE FROM topics WHERE project_id = $1
func (q *Queries) RemoveTopicsByProjectID(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTopicsByProjectID, projectID)
	return err
}

const shiftTopics = `-- name: ShiftTopics :exec
UPDATE topics
SET sort_order = sort_order + $2
WHERE parent_id = $1 and sort_order >= $3
`

type ShiftTopicsParams struct {
	ParentID pgtype.UUID
	Amount   int32
	Start    int32
}

// ShiftTopics
//
//	UPDATE topics
//	SET sort_order = sort_order + $2
//	WHERE parent_id = $1 and sort_order >= $3
func (q *Queries) ShiftTopics(ctx context.Context, arg ShiftTopicsParams) error {
	_, err := q.db.Exec(ctx, shiftTopics, arg.ParentID, arg.Amount, arg.Start)
	return err
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics
SET title = $2, content = $3, updated_at = now()
WHERE id = $1
RETURNING id, title, content, parent_id, project_id, sort_order, created_at, updated_at
`

type UpdateTopicParams struct {
	ID      pgtype.UUID
	Title   string
	Content string
}

// UpdateTopic
//
//	UPDATE topics
//	SET title = $2, content = $3, updated_at = now()
//	WHERE id = $1
//	RETURNING id, title, content, parent_id, project_id, sort_order, created_at, updated_at
func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic, arg.ID, arg.Title, arg.Content)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ParentID,
		&i.ProjectID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
