// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_query.sql

package orm

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (username) VALUES($1)
RETURNING id, username, created_at, updated_at
`

// CreateUser
//
//	INSERT INTO users (username) VALUES($1)
//	RETURNING id, username, created_at, updated_at
func (q *Queries) CreateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuthenticationMethod = `-- name: GetUserByAuthenticationMethod :one
SELECT users.id, users.username, users.created_at, users.updated_at, authentication_methods.id, authentication_methods.provider, authentication_methods.sub, authentication_methods.user_id, authentication_methods.created_at, authentication_methods.updated_at FROM users
JOIN authentication_methods ON authentication_methods.user_id = users.id
WHERE authentication_methods.provider = $1 AND authentication_methods.sub = $2
LIMIT 1
`

type GetUserByAuthenticationMethodParams struct {
	Provider AuthenticationProvider
	Sub      string
}

type GetUserByAuthenticationMethodRow struct {
	User                 User
	AuthenticationMethod AuthenticationMethod
}

// GetUserByAuthenticationMethod
//
//	SELECT users.id, users.username, users.created_at, users.updated_at, authentication_methods.id, authentication_methods.provider, authentication_methods.sub, authentication_methods.user_id, authentication_methods.created_at, authentication_methods.updated_at FROM users
//	JOIN authentication_methods ON authentication_methods.user_id = users.id
//	WHERE authentication_methods.provider = $1 AND authentication_methods.sub = $2
//	LIMIT 1
func (q *Queries) GetUserByAuthenticationMethod(ctx context.Context, arg GetUserByAuthenticationMethodParams) (GetUserByAuthenticationMethodRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthenticationMethod, arg.Provider, arg.Sub)
	var i GetUserByAuthenticationMethodRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.AuthenticationMethod.ID,
		&i.AuthenticationMethod.Provider,
		&i.AuthenticationMethod.Sub,
		&i.AuthenticationMethod.UserID,
		&i.AuthenticationMethod.CreatedAt,
		&i.AuthenticationMethod.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, created_at, updated_at FROM users
WHERE id = $1
`

// GetUserByID
//
//	SELECT id, username, created_at, updated_at FROM users
//	WHERE id = $1
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, updated_at = now()
WHERE id = $1
RETURNING id, username, created_at, updated_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID
	Username string
}

// UpdateUser
//
//	UPDATE users
//	SET username = $2, updated_at = now()
//	WHERE id = $1
//	RETURNING id, username, created_at, updated_at
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
