apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailhog
spec:
  secretName: mailhog-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - mailhog.local
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer