// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"fr_FR": &dictionary{index: fr_FRIndex, data: fr_FRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s's overview": 25,
	"About us":      0,
	"Cancel":        23,
	"Connect":       37,
	"Content":       32,
	"Create":        13,
	"Created at":    18,
	"Delete this items and its %d descendants ?": 33,
	"Discard unsaved changes ?":                  21,
	"Edit":                                       15,
	"Email Address":                              6,
	"Home":                                       8,
	"Just enter your email, and we’ll send you a magic link to sign in securely. No need to remember complicated passwords or create an account. This method is fast, safe, and respects your privacy—we only use your email to send the login link. Check your inbox, click the link, and you’re in. That’s it!": 3,
	"Logout":                      36,
	"My project":                  12,
	"My topic":                    35,
	"Overview":                    16,
	"Owner":                       26,
	"Passwordless Authentication": 2,
	"Profile":                     14,
	"Project's name":              11,
	"Save":                        22,
	"Send Magic Link":             7,
	"The content should be less than %d characters":  31,
	"The email is invalid":                           5,
	"The email is required":                          4,
	"The name is required":                           9,
	"The name should be less than %d characters":     10,
	"The parent is required":                         34,
	"The title is required":                          28,
	"The title should be less than %d characters":    29,
	"The username is required":                       19,
	"The username should be less than %d characters": 20,
	"Title":         24,
	"Topic count":   27,
	"Topic's title": 30,
	"Username":      17,
	"Welcome to your new productivity sidekick!\nWe’re here to help you get more done, without all the unnecessary fluff.\nKeep it simple, stay organized, and let’s crush those to-do lists together.\nLet’s make productivity less of a hassle and more of a habit!": 1,
}

var en_USIndex = []uint32{ // 39 elements
	// Entry 0 - 1F
	0x00000000, 0x00000009, 0x0000010d, 0x00000129,
	0x0000025d, 0x00000273, 0x00000288, 0x00000296,
	0x000002a6, 0x000002ab, 0x000002c0, 0x000002ee,
	0x000002fd, 0x00000308, 0x0000030f, 0x00000317,
	0x0000031c, 0x00000325, 0x0000032e, 0x00000339,
	0x00000352, 0x00000384, 0x0000039e, 0x000003a3,
	0x000003aa, 0x000003b0, 0x000003c1, 0x000003c7,
	0x000003d3, 0x000003e9, 0x00000418, 0x00000426,
	// Entry 20 - 3F
	0x00000457, 0x0000045f, 0x0000048d, 0x000004a4,
	0x000004ad, 0x000004b4, 0x000004bc,
} // Size: 180 bytes

const en_USData string = "" + // Size: 1212 bytes
	"\x02About us\x02Welcome to your new productivity sidekick!\x0aWe’re here" +
	" to help you get more done, without all the unnecessary fluff.\x0aKeep i" +
	"t simple, stay organized, and let’s crush those to-do lists together." +
	"\x0aLet’s make productivity less of a hassle and more of a habit!\x02Pas" +
	"swordless Authentication\x02Just enter your email, and we’ll send you a " +
	"magic link to sign in securely. No need to remember complicated password" +
	"s or create an account. This method is fast, safe, and respects your pri" +
	"vacy—we only use your email to send the login link. Check your inbox, cl" +
	"ick the link, and you’re in. That’s it!\x02The email is required\x02The " +
	"email is invalid\x02Email Address\x02Send Magic Link\x02Home\x02The name" +
	" is required\x02The name should be less than %[1]d characters\x02Project" +
	"'s name\x02My project\x02Create\x02Profile\x02Edit\x02Overview\x02Userna" +
	"me\x02Created at\x02The username is required\x02The username should be l" +
	"ess than %[1]d characters\x02Discard unsaved changes ?\x02Save\x02Cancel" +
	"\x02Title\x02%[1]s's overview\x02Owner\x02Topic count\x02The title is re" +
	"quired\x02The title should be less than %[1]d characters\x02Topic's titl" +
	"e\x02The content should be less than %[1]d characters\x02Content\x02Dele" +
	"te this items and its %[1]d descendants ?\x02The parent is required\x02M" +
	"y topic\x02Logout\x02Connect"

var fr_FRIndex = []uint32{ // 39 elements
	// Entry 0 - 1F
	0x00000000, 0x00000012, 0x0000012f, 0x00000152,
	0x0000030e, 0x00000322, 0x00000338, 0x00000347,
	0x0000035f, 0x00000367, 0x00000379, 0x000003a9,
	0x000003b7, 0x000003c2, 0x000003c9, 0x000003d0,
	0x000003d9, 0x000003e1, 0x000003f3, 0x000003fd,
	0x0000041d, 0x0000045b, 0x00000489, 0x00000495,
	0x0000049d, 0x000004a3, 0x000004b4, 0x000004c2,
	0x000004d3, 0x000004e7, 0x00000519, 0x00000528,
	// Entry 20 - 3F
	0x0000055c, 0x00000564, 0x00000597, 0x000005ac,
	0x000005b6, 0x000005c6, 0x000005d3,
} // Size: 180 bytes

const fr_FRData string = "" + // Size: 1491 bytes
	"\x02À propos de nous\x02Bienvenue à votre nouveau compagnon de productiv" +
	"ité !\x0aNous sommes là pour vous aider à en faire plus, sans tout le su" +
	"perflu inutile.\x0aRestez simple, restez organisé, et ensemble, écrasons" +
	" ces listes de tâches.\x0aFaisons de la productivité moins une corvée et" +
	" plus une habitude !\x02Authentification sans mot de passe\x02Il vous su" +
	"ffit d’entrer votre adresse e-mail, et nous vous enverrons un lien magiq" +
	"ue pour vous connecter en toute sécurité. Pas besoin de retenir des mots" +
	" de passe compliqués ni de créer un compte. Cette méthode est rapide, sû" +
	"re et respecte votre vie privée — nous utilisons uniquement votre e-mail" +
	" pour envoyer le lien de connexion. Consultez votre boîte de réception, " +
	"cliquez sur le lien, et vous êtes connecté. C’est tout !\x02L'e-mail est" +
	" requis\x02L'e-mail est invalide\x02Adresse e-mail\x02Envoyer le lien ma" +
	"gique\x02Accueil\x02Le nom est requis\x02Le nom doit contenir moins de %" +
	"[1]d caractères\x02Nom du projet\x02Mon projet\x02Créer\x02Profil\x02Mod" +
	"ifier\x02Aperçu\x02Nom d'utilisateur\x02Créé le\x02Le nom d'utilisateur " +
	"est requis\x02Le nom d'utilisateur doit contenir moins de %[1]d caractèr" +
	"es\x02Annuler les modifications non enregistrées ?\x02Enregistrer\x02Ann" +
	"uler\x02Titre\x02Aperçu de %[1]s\x02Propriétaire\x02Nombre de sujets\x02" +
	"Le titre est requis\x02Le titre doit contenir moins de %[1]d caractères" +
	"\x02Titre du sujet\x02Le contenu doit contenir moins de %[1]d caractères" +
	"\x02Contenu\x02Supprimer cet élément et ses %[1]d descendants ?\x02Le pa" +
	"rent est requis\x02Mon sujet\x02Se déconnecter\x02Se connecter"

	// Total table size 3063 bytes (2KiB); checksum: B24394C7
